Update august
inbo/reporting-rshiny-grofwildjacht pull request #234
Opened 2021-08-06 09:18 UTC by dbemelmans

#222, #226, #227, #232, #233 should be solved now.

2021-08-09 05:14 UTC, SanderDevisscher requested changes
FIGUUR: Verdeling afschot over de jaren:
- [ ] Grafiek blijft zich resetten na wijziging periode

https://user-images.githubusercontent.com/16779320/128662803-cc9495e9-eab5-4398-ad94-d6ee50c93f7d.mp4

- [ ] Volgorde balken per seizoen is nu `zomer, winter, lente en herfst` dit zou `lente, zomer, herfst en winter` moeten worden
- [ ] Volgorde van de ander intervallen moeten ook nog nagekeken worden

2021-08-09 05:29 UTC, SanderDevisscher requested changes
@jimcasaer in 2021 werden 2 zwijnen geschoten in Laarne, enig idee of dit klopt ? of moeten we eens horen bij ANB ?

2021-08-09 05:49 UTC, SanderDevisscher commented
@jimcasaer in 2021 werden 2 zwijnen geschoten in Laarne, enig idee of dit klopt ? of moeten we eens horen bij ANB ?

2021-08-09 11:55 UTC, jimcasaer commented
![image](https://user-images.githubusercontent.com/17747176/128702278-3202f942-1ea3-403d-bad0-bba927e615eb.png)

2021-08-09 11:58 UTC, jimcasaer commented
![image](https://user-images.githubusercontent.com/17747176/128702680-e5be8209-6b4d-4e5c-9621-1b1ccb2b17e4.png)

2021-08-09 14:36 UTC, SanderDevisscher commented
@dbemelmans lukt het om #235 nog aan te passen voor woensdag ?

2021-08-09 14:46 UTC, SanderDevisscher commented
Blijkbaar wel :-D

2021-08-10 08:44 UTC, SanderDevisscher approved these changes

2021-08-10 08:44 UTC, merged