218 test wbe
inbo/reporting-rshiny-grofwildjacht pull request #333
Opened 2022-09-20 18:40 UTC by mvarewyck

closes #327, #310, #304, #303, #302, #264

2022-09-21 07:38 UTC, SanderDevisscher requested changes
When building docker container using powershell <sup>1</sup>

```
I get the following error:
 > [15/17] RUN R CMD INSTALL /root/reporting-grofwild.tar.gz:
#19 3.760 * installing to library ‘/usr/local/lib/R/site-library’
#19 3.776 * installing *source* package ‘reportingGrofwild’ ...
#19 3.776 ** using staged installation
#19 3.791 ** R
#19 3.828 Error in parse(outFile) :
#19 3.828   /tmp/RtmpCTzVR4/R.INSTALLc4e8f66b6/reportingGrofwild/R/utils.R:318:0: unexpected end of input
#19 3.828 316:
#19 3.828 317: }
#19 3.828     ^
#19 3.828 ERROR: unable to collate and parse R files for package ‘reportingGrofwild’
#19 3.828 * removing ‘/usr/local/lib/R/site-library/reportingGrofwild’
------
executor failed running [/bin/sh -c R CMD INSTALL /root/$latestApp]: exit code: 1
```

<sup>1</sup> steps:

1. fetch branch
2. open .rproj
3. run `devtools::build(pkg = "reporting-grofwild")`
4. rename tarball to `reporting-grofwild.tar.gz`
5. open powershell 
6. run `cd documents/github/reporting-rshiny-grofwildjacht`
7. run `docker build -t openanalytics/wildapp .`

2022-09-21 08:31 UTC, mvarewyck commented
@SanderDevisscher Could you try again?

2022-09-26 08:47 UTC, SanderDevisscher commented
@mvarewyck do you convert back to ready for review when I can try again ?

2022-09-28 13:28 UTC, SanderDevisscher requested changes
I now get the following error:

```
Warning in readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file '/usr/local/lib/R/site-library/reportingGrofwild/extdata/spatialDataWBE.RData', probable reason 'No such file or directory'
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: <Anonymous> ... eval -> eval -> ..stacktraceon.. -> load -> readChar
Execution halted
```

2022-09-28 13:30 UTC, SanderDevisscher commented
And this similar error when I run `docker run -p 3857:3838 openanalytics/wildapp R -e "reportingGrofwild::runWildApp(public=TRUE)"`

```
Warning in readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file '/usr/local/lib/R/site-library/reportingGrofwild/extdata/spatialData.RData', probable reason 'No such file or directory'
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: <Anonymous> ... eval -> eval -> ..stacktraceon.. -> load -> readChar
Execution halted
```

2022-09-28 13:32 UTC, SanderDevisscher commented
And exactly the same initial error when I run  `docker run -p 3857:3838 openanalytics/wildapp R -e 'reportingGrofwild::runWildApp(public=FALSE, kbo = 15284586)'`

2022-09-29 08:00 UTC, mvarewyck commented
This is because these .Rdata files are no longer tracked by GIT (due to their large size).
* You can create these data yourself in R: 
```
devtools::load_all(path = "~/git/reporting-rshiny-grofwildjacht/reporting-grofwild")
createShapeData()
```
Then build the R package and use this one in docker.
* Alternatively, I can put the latest version on the S3 bucket and you download them from there

2022-09-29 08:02 UTC, SanderDevisscher commented
Is it possible to store them on the s3 bucket and make the app load them from there ?

2022-09-29 08:03 UTC, SanderDevisscher commented
but that would be difficult for use in docker, right ?

2022-09-29 09:18 UTC, SanderDevisscher commented
I get this error when running  `devtools::load_all(path = "./git/reporting-rshiny-grofwildjacht/reporting-grofwild")`
```
Error in `value[[3L]]()`:
! Could not find a root 'DESCRIPTION' file that starts with '^Package' in 'C:\Users\sander_devisscher\Documents\GitHub\reporting-rshiny-grofwildjacht\git\reporting-rshiny-grofwildjacht\reporting-grofwild'. Are you in your project directory, and does your project have a 'DESCRIPTION' file?
Run `rlang::last_error()` to see where the error occurred.
Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="./git/reporting-rshiny-grofwildjacht/reporting-grofwild": Het systeem kan het opgegeven pad niet vinden
```

2022-09-29 09:24 UTC, SanderDevisscher commented
When I run `devtools::load_all(path = "./reporting-grofwild")` it loads without issues.
but then I get this error when I run `createShapeData()`
`Error in createShapeData() : could not find function "createShapeData"`

2022-10-03 08:51 UTC, mvarewyck commented
Sorry, in this branch the function is called `readShapeData()`

2022-10-03 09:17 UTC, SanderDevisscher commented
builden lukt nu wel

2022-10-03 09:46 UTC, SanderDevisscher requested changes
![image](https://user-images.githubusercontent.com/16779320/193545790-fbf9d336-3ac8-4b76-ae20-032f80b7d7b0.png)

Startyear of slider != startyear of graph
for the rest the slider works as expected

same isssue with FIGUUR: Gewicht per jaar & FIGUUR: Onderkaaklengte per jaar (INBO of Meldingsformulier)

voorbeeld WBE Voeren

voor de rest zie ik geen breaking issues 

PS admin account werkt ook !!

2022-10-03 09:49 UTC, SanderDevisscher commented
@mvarewyck na het mergen van #314 zijn er blijkbaar een aantal conflicten ontstaan. Kan je hier ook eens naar kijken ?

2022-10-03 13:40 UTC, SanderDevisscher commented
@mvarewyck mag ik deze PR al terug testen ?

2022-10-03 14:27 UTC, mvarewyck commented
> ue with FIGUUR: Gewicht per jaar & FIGUUR: Onderkaaklengte per jaar (INBO of Meldingsformulier)

* Voor leeggewicht & onderkaaklengte: Wanneer je alle types selecteert, is er wel data vanaf 2014, dus voor deze fig zou ik het op 2014 laten starten.
Veel records voor 2014-2015 worden uitgesloten wegens ontbrekende `geslacht_comp_bron` terwijl `type_comp` wel gekend is.
* Voor embryos is er idd pas *female* data vanaf 2016 (male vanaf 2014). Daarvoor zal ik de slider aanpassen.

> @mvarewyck mag ik deze PR al terug testen ?

Ja.

2022-10-03 14:49 UTC, mvarewyck commented
> Startyear of slider != startyear of graph for the rest the slider works as expected

Er zijn volgens mij 2 opties:
* Behoud oude code: startyear slider = 2014 geeft dan veel missings aangeduid in tekst onder de figuur. Wanneer gebruiker de slider op 2016 zet, zal het percentage stijgen (figuur blijft dezelfde - zie hieronder)
* Slider laten starten op 2016: Gebruiker kan 2014-2015 niet selecteren omdat we jaartal slider baseren op data waarvoor `type_comp` van vrouwelijk geslacht gekend zijn

![Screenshot from 2022-10-03 16-42-36](https://user-images.githubusercontent.com/22143743/193607162-8a46067f-6b39-4151-a3f8-c4fd4a516a70.png)

2022-10-03 14:53 UTC, SanderDevisscher commented
@mvarewyck ik zou hier kiezen voor optie 2: slider laten afhangen van de data en dus laten starten vanaf 2016

2022-10-03 15:45 UTC, SanderDevisscher approved these changes

2022-10-03 15:46 UTC, merged