356 hotfix wbe
inbo/reporting-rshiny-grofwildjacht pull request #371
Opened 2023-01-09 14:34 UTC by mvarewyck

Update wrt no data disclaimers

2023-01-23 17:33 UTC, SanderDevisscher commented
mag dicht wegens gemerged into #376 ?

2023-01-23 19:16 UTC, mvarewyck commented
> mag dicht wegens gemerged into #376 ?

nee, #376 is nu in deze branch gemerged

2023-01-24 15:57 UTC, SanderDevisscher commented
@mvarewyck ik zet deze PR nog even op draft tot we #306 volledig hebben uitgeklaard

2023-01-27 12:03 UTC, SanderDevisscher commented
Ik wacht nog even op feedback van @jimcasaer, @LynnPallemaerts of @RuttenAnneleen ivm de disclaimer bij het afschotkaartje (zie [15c6683](https://github.com/inbo/reporting-rshiny-grofwildjacht/pull/371/commits/15c6683508251902d3ecc816fd9cf6e0517d38e5))

2023-01-27 13:42 UTC, SanderDevisscher requested changes
De filter van de afschotlocaties werkt nog niet zoals het zou moeten, zie screenshot onder:

![image](https://user-images.githubusercontent.com/16779320/215101181-9a985082-3a23-44db-a34b-d6a3e3e7e183.png)

2023-01-30 10:37 UTC, RuttenAnneleen approved these changes

2023-01-30 10:38 UTC, RuttenAnneleen approved these changes

2023-02-02 08:48 UTC, SanderDevisscher commented
@RuttenAnneleen heb je dit via docker getest ?

2023-02-02 08:51 UTC, RuttenAnneleen commented
> @RuttenAnneleen heb je dit via docker getest ?

Nee, moet ik dat doen dan?

2023-02-02 08:52 UTC, SanderDevisscher commented
> > @RuttenAnneleen heb je dit via docker getest ?
> 
> Nee, moet ik dat doen dan?

Best wel ja, hoe weet je anders of alles werkt zoals het zou moeten?

2023-02-02 08:54 UTC, SanderDevisscher commented
Ook willen we het aantal deploys op de UAT/PRD tot een minimum te beperken => goed "lokaal" testen is hiervoor de key

2023-02-02 08:54 UTC, RuttenAnneleen commented
> > > @RuttenAnneleen heb je dit via docker getest ?
> > 
> > 
> > Nee, moet ik dat doen dan?
> 
> Best wel ja, hoe weet je anders of alles werkt zoals het zou moeten?

Ik dacht dat het enkel een kwestie was van de tekst die aangepast moet worden maar ik kijk het na via docker!

2023-02-02 10:08 UTC, SanderDevisscher requested changes
De n waardes op deze grafieken overlapt met de databeschikbaarheid disclaimer. Ik stel voor dat we deze waarde verhuizen naar de plotly popup. 

FIGUUR: Afschot per jachtmethode:
![newplot(2)](https://user-images.githubusercontent.com/16779320/216294294-d61cf5d7-2cfd-4547-bd27-4e8bb4f06876.png) 

PS dit is in het publieke deel. Ik kijk nu het private deel na.

2023-02-02 10:16 UTC, SanderDevisscher commented
@mvarewyck klopt het dat er nog geen tekstveld voorzien is voor de Biotoop beschrijving ?

2023-02-02 10:37 UTC, SanderDevisscher commented
Op onderstaande issues na  ziet het er goed uit!

- [ ] n - values -> plotly popup
- [ ] tekst voor biotoop beschrijving (berekend o.b.v. corinne landgebruik laag)
- [ ] periode in disclaimer == geselecteerde periode

2023-02-02 13:52 UTC, SanderDevisscher approved these changes

2023-02-02 13:52 UTC, merged